# Generated by Django 5.2.5 on 2025-08-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='category',
        ),
        migrations.AddField(
            model_name='shoe',
            name='categories',
            field=models.ManyToManyField(related_name='shoes', to='shoes.category'),
        ),
    ]
