# Generated by Django 5.2.5 on 2025-08-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_remove_shoe_category_shoe_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='categories',
        ),
        migrations.AddField(
            model_name='shoe',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes.category'),
        ),
    ]
