# Generated by Django 5.2.5 on 2025-08-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_remove_shoe_categories_shoe_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='categories',
        ),
        migrations.AddField(
            model_name='shoe',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='shoes', to='shoes.category'),
        ),
    ]
